services:

  postgres_db:
    image: pgvector/pgvector:pg16
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${DB_USER:-Danh}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-1234}
      POSTGRES_DB: ${DB_NAME:-ecom}
    ports:
      - "5433:5432"
    labels:
      org.springframework.boot.service-connection: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-Danh} -d ${DB_NAME:-ecom}" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
