spring.datasource.url=jdbc:postgresql://localhost:5432/demo
spring.datasource.username=postgres
spring.datasource.password=060233
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
#Spring.jpa.show-sql=true



#chat model
spring.ai.google.genai.api-key=${GOOGLE_AI_API_KEY}
spring.ai.google.genai.project-id=${GOOGLE_AI_PROJECT_ID}
spring.ai.google.genai.chat.model=gemini-3.5-flash

#pg vector
spring.ai.google.genai.embedding.api-key=${GOOGLE_AI_API_KEY}
spring.ai.google.genai.embedding.project-id=${GOOGLE_AI_PROJECT_ID}
spring.ai.google.genai.embedding.text.dimensions= 768
#spring.ai.vectorstore.pgvector.initialize-schema=true

spring.docker.compose.file=docker-compose-dev.yml